[package]
authors = ["ryan <ryan@kurte.nz>"]
edition = "2018"
name = "dsf-client"
version = "0.1.0"
publish = false

[dependencies]
futures = "0.3.1"
async-std = "1.3.0"
actix = "0.8.3"
tokio = "0.2.4"
tokio-codec = "0.1.1"
tokio-uds = "0.2.5"
colored = "1.9.0"
serde_json= "1.0.44"
tracing = "0.1.10"
tracing-futures = "0.2.0"
futures_codec = "0.3.4"
async-trait = "0.1.19"


[dependencies.dsf-core]
path = "../dsf-core"
features = [ "serde" ]

[dependencies.dsf-rpc]
path = "../dsf-rpc"

[dependencies.daemon-engine]
git = "https://github.com/ryankurte/rust-daemon"

[dependencies.log]
features = ["max_level_trace", "release_max_level_info"]
version = "0.4.6"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.6"

