name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc --no-deps
    - name: Publish docs
      uses: crazy-max/ghaction-github-pages@v1.2.4
      with:
        build_dir: target/doc
